version: '3'
services:
    web:
        image: nginx:latest
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached"
            - "./project:/var/www/html:cached"
        ports:
            - "8008:80"
        command: "nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysql


    mix:
        build: ./docker/node
        working_dir: "/var/www/html/"
        #command: 'npm start'
        #if you need add npm start: laravel-echo-server start command to package.json
        volumes:
            - "./project:/var/www/html:cached"
        ports:
            - 8888:8888
        depends_on:
            - web

    php:
        build: ./docker/php
        restart: always
        volumes:
            - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini:cached
            - ./project:/var/www/html:cached
        links:
            - mysql
        environment:
            PHP_IDE_CONFIG: "serverName=lvs.portfolio.local"

    mysql:
        image: mysql:5.7
        restart: always
        ports:
            - "3308:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - "./etc/mysql/my.cnf:/etc/mysql/my.cnf:cached"
            - "./data/db/mysql:/var/lib/mysql:cached"